# Query Yahoo Fantasy Iceberg Tables

This notebook demonstrates how to load and query the Yahoo Fantasy data stored in Iceberg tables.

The notebook correctly handles Windows path resolution by:
1. Finding the project root from `pyproject.toml`
2. Using absolute paths for the Iceberg catalog
3. Using the correct warehouse location

## Setup

In [5]:
%load_ext autotime

time: 0 ns (started: 2026-07-23 17:30:21 -05:00)

In [ ]:
from nfl.yahoo_fantasy import (
    YahooWarehouseClient,
    WarehouseQueryError,
    average_scoring_by_position_by_team,
    configure_polars_display,
    enrich_weekly_team_points,
    format_table_for_display,
    league_average_by_position,
    league_team_info,
    make_table_loaders,
    player_points_health,
    standings_summary as query_standings_summary,
    weekly_team_points_resolved,
)

time: 1.72 s (started: 2026-07-23 17:30:21 -05:00)

In [ ]:
# Configure Polars display and table presentation mode
configure_polars_display(rows=50, cols=20, str_length=100)

time: 0 ns (started: 2026-07-23 17:30:22 -05:00)

In [ ]:
# Initialize query client from repository root and register metadata if needed.
try:
    client = YahooWarehouseClient.from_project_root()
except WarehouseQueryError as exc:
    raise RuntimeError(f"Warehouse client initialization failed: {exc}") from exc

report = client.ensure_registered()

project_root = client.paths.project_root
CATALOG_DB_PATH = client.paths.catalog_db_path
WAREHOUSE_PATH = client.paths.warehouse_path
CATALOG_URI = client.paths.catalog_uri
WAREHOUSE_URI = client.paths.warehouse_uri

# Anchor cwd to repo root so relative metadata paths resolve to ./warehouse instead of examples/warehouse.
import os
os.chdir(project_root)

print("✓ Warehouse query client loaded.")
print("  Project root:", project_root)
print("  CWD:", os.getcwd())
print("  Catalog URI:", CATALOG_URI)
print("  Warehouse path:", WAREHOUSE_PATH)
print("  Registration report:", report)

✓ Warehouse query client loaded.
  Project root: C:\Users\EricTruett\nfl
  CWD: C:\Users\EricTruett\nfl
  Catalog URI: sqlite:///C:/Users/EricTruett/nfl/iceberg_catalog.db
  Warehouse path: C:\Users\EricTruett\nfl\warehouse
  Registration report: RegistrationReport(normalized_rows=0, registered_tables=0, tables_before=11, tables_after=11)
time: 1.12 s (started: 2026-07-23 17:30:22 -05:00)

## Functions

In [ ]:
def show_table(df, drop_keys: bool = True):
    """Display a table, optionally dropping key/id columns and rounding floats/decimals."""
    display(format_table_for_display(df, drop_keys=drop_keys))

time: 16 ms (started: 2026-07-23 17:30:23 -05:00)

In [ ]:
# Utility functions for loading tables
_, maybe_load = make_table_loaders(client)

time: 0 ns (started: 2026-07-23 17:30:24 -05:00)

## Get Warehouse Information

In [11]:
if CATALOG_DB_PATH.exists():
    print("✓ Catalog database exists:", CATALOG_DB_PATH)
else:
    print("⚠ Catalog database does not exist yet:", CATALOG_DB_PATH)
    print("  It will be created on first write operation.")

✓ Catalog database exists: C:\Users\EricTruett\nfl\iceberg_catalog.db
time: 16 ms (started: 2026-07-23 17:30:24 -05:00)

In [12]:
# List available tables with library helpers.
namespaces = ["yahoo_common", "yhnfl"]
all_tables: dict[str, list[str]] = {}

for ns in namespaces:
    all_tables[ns] = client.list_tables(ns)

print("Available tables:\n")
for ns in namespaces:
    print(f"{ns}:")
    if all_tables[ns]:
        for t in all_tables[ns]:
            print(f"  - {t}")
    else:
        print("  (no tables found)")

Available tables:

yahoo_common:
  - yahoo_common.draft_pick
  - yahoo_common.league
  - yahoo_common.player
  - yahoo_common.scoring_rule
  - yahoo_common.stat_category
  - yahoo_common.team
  - yahoo_common.transaction
yhnfl:
  - yhnfl.matchups
  - yhnfl.player_stats_weekly
  - yhnfl.roster_entries
  - yhnfl.standings
time: 0 ns (started: 2026-07-23 17:30:24 -05:00)

## Example 1: League and Team Information

Load league and team data to see league context per team.

In [13]:
league_df = maybe_load("yahoo_common.league")
team_df = maybe_load("yahoo_common.team")

league_team = league_team_info(league_df=league_df, team_df=team_df)
print("League and Team Information:")
show_table(league_team)

League and Team Information:

shape: (12, 4)
┌────────┬─────────────┬───────────────────────┬─────────────┐
│ season ┆ league_name ┆ team_name             ┆ owner_name  │
│ ---    ┆ ---         ┆ ---                   ┆ ---         │
│ i64    ┆ str         ┆ str                   ┆ str         │
╞════════╪═════════════╪═══════════════════════╪═════════════╡
│ 2025   ┆ Dilly Dilly ┆ DaSaints              ┆ Reggy       │
│ 2025   ┆ Dilly Dilly ┆ Kyler the Creator     ┆ Alexander   │
│ 2025   ┆ Dilly Dilly ┆ Action is the Juice   ┆ Eric        │
│ 2025   ┆ Dilly Dilly ┆ oooutzs               ┆ Arlo        │
│ 2025   ┆ Dilly Dilly ┆ Alameda All-Stars     ┆ Mr. T       │
│ 2025   ┆ Dilly Dilly ┆ Tompa Bae             ┆ Jesse       │
│ 2025   ┆ Dilly Dilly ┆ Kzoo Killaz           ┆ Drew        │
│ 2025   ┆ Dilly Dilly ┆ Raven-ous             ┆ Moon        │
│ 2025   ┆ Dilly Dilly ┆ Pukachu I choose you! ┆ Christopher │
│ 2025   ┆ Dilly Dilly ┆ Rome Sweet Rome       ┆ Kevin       │
│ 2025   ┆ Dilly Dilly ┆ Zero Dark Purdy       ┆ Matt        │
│ 2025   ┆ Dilly Dilly ┆ I am the Tank         ┆ Nbones      │
└────────┴─────────────┴───────────────────────┴─────────────┘

time: 360 ms (started: 2026-07-23 17:30:24 -05:00)

## Example 2: NFL League Standings

Load standings data to rank teams by wins and points for.

In [14]:
STANDINGS_TABLE = "yhnfl.standings"
standings_df = None
league_df = maybe_load("yahoo_common.league")
team_df = maybe_load("yahoo_common.team")

try:
    standings_df = client.load_table(STANDINGS_TABLE)
except Exception as exc:
    print(f"Initial standings load failed for {STANDINGS_TABLE}: {exc}")

if standings_df is None:
    # Recover common notebook state issues by re-running registration once and retrying.
    _ = client.ensure_registered(namespaces=["yhnfl"])
    try:
        standings_df = client.load_table(STANDINGS_TABLE)
    except Exception as exc:
        print(f"Retry standings load failed for {STANDINGS_TABLE}: {exc}")

if standings_df is not None and league_df is not None and team_df is not None:
    standings_summary = query_standings_summary(
        standings_df=standings_df,
        league_df=league_df,
        team_df=team_df,
    )
    print("NFL League Standings:")
    show_table(standings_summary)
else:
    print(f"Missing required data for {STANDINGS_TABLE} standings view.")
    print("Available yhnfl tables:")
    print(client.list_tables("yhnfl"))

NFL League Standings:

shape: (12, 9)
┌────────┬─────────────┬─────────────┬────────────┬──────┬──────┬────────┬────────────┬────────────┐
│ season ┆ league_name ┆ team_name   ┆ owner_name ┆ rank ┆ wins ┆ losses ┆ points_for ┆ points_aga │
│ ---    ┆ ---         ┆ ---         ┆ ---        ┆ ---  ┆ ---  ┆ ---    ┆ ---        ┆ inst       │
│ i64    ┆ str         ┆ str         ┆ str        ┆ i64  ┆ i64  ┆ i64    ┆ f64        ┆ ---        │
│        ┆             ┆             ┆            ┆      ┆      ┆        ┆            ┆ f64        │
╞════════╪═════════════╪═════════════╪════════════╪══════╪══════╪════════╪════════════╪════════════╡
│ 2025   ┆ Dilly Dilly ┆ Pukachu I   ┆ Christophe ┆ 4    ┆ 11   ┆ 3      ┆ 1854.52    ┆ 1540.48    │
│        ┆             ┆ choose you! ┆ r          ┆      ┆      ┆        ┆            ┆            │
│ 2025   ┆ Dilly Dilly ┆ Action is   ┆ Eric       ┆ 1    ┆ 10   ┆ 4      ┆ 1838.4     ┆ 1672.76    │
│        ┆             ┆ the Juice   ┆            ┆      ┆      ┆        ┆            ┆            │
│ 2025   ┆ Dilly Dilly ┆ Rome Sweet  ┆ Kevin      ┆ 3    ┆ 9    ┆ 5      ┆ 1986.66    ┆ 1787.14    │
│        ┆             ┆ Rome        ┆            ┆      ┆      ┆        ┆            ┆            │
│ 2025   ┆ Dilly Dilly ┆ DaSaints    ┆ Reggy      ┆ 5    ┆ 9    ┆ 5      ┆ 1756.88    ┆ 1737.22    │
│ 2025   ┆ Dilly Dilly ┆ oooutzs     ┆ Arlo       ┆ 2    ┆ 7    ┆ 7      ┆ 1705.1     ┆ 1675.52    │
│ 2025   ┆ Dilly Dilly ┆ Kzoo Killaz ┆ Drew       ┆ 6    ┆ 6    ┆ 8      ┆ 1760.54    ┆ 1817.88    │
│ 2025   ┆ Dilly Dilly ┆ Raven-ous   ┆ Moon       ┆ 10   ┆ 6    ┆ 8      ┆ 1644.88    ┆ 1730.42    │
│ 2025   ┆ Dilly Dilly ┆ Alameda     ┆ Mr. T      ┆ 9    ┆ 6    ┆ 8      ┆ 1623.92    ┆ 1558.48    │
│        ┆             ┆ All-Stars   ┆            ┆      ┆      ┆        ┆            ┆            │
│ 2025   ┆ Dilly Dilly ┆ Tompa Bae   ┆ Jesse      ┆ 8    ┆ 6    ┆ 8      ┆ 1571.74    ┆ 1621.78    │
│ 2025   ┆ Dilly Dilly ┆ Zero Dark   ┆ Matt       ┆ 7    ┆ 5    ┆ 9      ┆ 1645.86    ┆ 1785.66    │
│        ┆             ┆ Purdy       ┆            ┆      ┆      ┆        ┆            ┆            │
│ 2025   ┆ Dilly Dilly ┆ I am the    ┆ Nbones     ┆ 12   ┆ 5    ┆ 9      ┆ 1576.0     ┆ 1901.32    │
│        ┆             ┆ Tank        ┆            ┆      ┆      ┆        ┆            ┆            │
│ 2025   ┆ Dilly Dilly ┆ Kyler the   ┆ Alexander  ┆ 11   ┆ 4    ┆ 10     ┆ 1427.66    ┆ 1563.5     │
│        ┆             ┆ Creator     ┆            ┆      ┆      ┆        ┆            ┆            │
└────────┴─────────────┴─────────────┴────────────┴──────┴──────┴────────┴────────────┴────────────┘

time: 94 ms (started: 2026-07-23 17:30:24 -05:00)

## Example 3: Weekly Fantasy Points by Team

This combines `yhnfl.player_stats_weekly` with `yhnfl.roster_entries` to summarize total fantasy points by week and team.

In [ ]:
stats_df = maybe_load("yhnfl.player_stats_weekly")
roster_df = maybe_load("yhnfl.roster_entries")
matchups_df = maybe_load("yhnfl.matchups")
league_df = maybe_load("yahoo_common.league")
team_df = maybe_load("yahoo_common.team")

weekly_points, points_source = weekly_team_points_resolved(
    stats_df=stats_df,
    roster_df=roster_df,
    matchups_df=matchups_df,
)

if points_source in {"player_stats", "matchups"}:
    weekly_points_display = enrich_weekly_team_points(
        weekly_points=weekly_points,
        league_df=league_df,
        team_df=team_df,
    )

    if points_source == "player_stats":
        print("Weekly Fantasy Points by Team (from player/roster stats):")
    else:
        print("Weekly Fantasy Points by Team (fallback from matchups.points):")
    show_table(weekly_points_display)
else:
    print("Required NFL weekly tables not found.")

Weekly Fantasy Points by Team (fallback from matchups.points):

shape: (196, 6)
┌────────┬──────┬─────────────┬───────────────────────┬─────────────┬─────────────┐
│ season ┆ week ┆ league_name ┆ team_name             ┆ owner_name  ┆ team_points │
│ ---    ┆ ---  ┆ ---         ┆ ---                   ┆ ---         ┆ ---         │
│ i64    ┆ i64  ┆ str         ┆ str                   ┆ str         ┆ f64         │
╞════════╪══════╪═════════════╪═══════════════════════╪═════════════╪═════════════╡
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ DaSaints              ┆ Reggy       ┆ 154.76      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Raven-ous             ┆ Moon        ┆ 132.18      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Pukachu I choose you! ┆ Christopher ┆ 123.84      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Kzoo Killaz           ┆ Drew        ┆ 122.72      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Zero Dark Purdy       ┆ Matt        ┆ 119.58      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Alameda All-Stars     ┆ Mr. T       ┆ 118.36      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Rome Sweet Rome       ┆ Kevin       ┆ 111.4       │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ I am the Tank         ┆ Nbones      ┆ 105.38      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Kyler the Creator     ┆ Alexander   ┆ 102.62      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Tompa Bae             ┆ Jesse       ┆ 101.92      │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ oooutzs               ┆ Arlo        ┆ 99.62       │
│ 2025   ┆ 1    ┆ Dilly Dilly ┆ Action is the Juice   ┆ Eric        ┆ 70.92       │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Rome Sweet Rome       ┆ Kevin       ┆ 231.48      │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Alameda All-Stars     ┆ Mr. T       ┆ 153.8       │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Action is the Juice   ┆ Eric        ┆ 133.84      │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Zero Dark Purdy       ┆ Matt        ┆ 131.66      │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Kzoo Killaz           ┆ Drew        ┆ 131.18      │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ DaSaints              ┆ Reggy       ┆ 126.62      │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ I am the Tank         ┆ Nbones      ┆ 125.28      │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Pukachu I choose you! ┆ Christopher ┆ 116.0       │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ oooutzs               ┆ Arlo        ┆ 110.5       │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Tompa Bae             ┆ Jesse       ┆ 87.14       │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Kyler the Creator     ┆ Alexander   ┆ 85.1        │
│ 2025   ┆ 2    ┆ Dilly Dilly ┆ Raven-ous             ┆ Moon        ┆ 84.14       │
│ 2025   ┆ 3    ┆ Dilly Dilly ┆ Action is the Juice   ┆ Eric        ┆ 146.22      │
│ …      ┆ …    ┆ …           ┆ …                     ┆ …           ┆ …           │
│ 2025   ┆ 15   ┆ Dilly Dilly ┆ Kzoo Killaz           ┆ Drew        ┆ 133.56      │
│ 2025   ┆ 15   ┆ Dilly Dilly ┆ oooutzs               ┆ Arlo        ┆ 128.14      │
│ 2025   ┆ 15   ┆ Dilly Dilly ┆ Tompa Bae             ┆ Jesse       ┆ 118.96      │
│ 2025   ┆ 15   ┆ Dilly Dilly ┆ Kyler the Creator     ┆ Alexander   ┆ 110.94      │
│ 2025   ┆ 15   ┆ Dilly Dilly ┆ DaSaints              ┆ Reggy       ┆ 106.52      │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Zero Dark Purdy       ┆ Matt        ┆ 180.08      │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Action is the Juice   ┆ Eric        ┆ 167.5       │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ oooutzs               ┆ Arlo        ┆ 157.16      │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Rome Sweet Rome       ┆ Kevin       ┆ 143.56      │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Kyler the Creator     ┆ Alexander   ┆ 138.3       │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Tompa Bae             ┆ Jesse       ┆ 129.52      │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Raven-ous             ┆ Moon        ┆ 127.0       │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Alameda All-Stars     ┆ Mr. T       ┆ 120.44      │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ DaSaints              ┆ Reggy       ┆ 114.3       │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ I am the Tank         ┆ Nbones      ┆ 113.3       │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Kzoo Killaz           ┆ Drew        ┆ 94.5        │
│ 2025   ┆ 16   ┆ Dilly Dilly ┆ Pukachu I choose you! ┆ Christopher ┆ 89.4        │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ Action is the Juice   ┆ Eric        ┆ 170.02      │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ Rome Sweet Rome       ┆ Kevin       ┆ 152.68      │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ Alameda All-Stars     ┆ Mr. T       ┆ 141.62      │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ Zero Dark Purdy       ┆ Matt        ┆ 139.36      │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ oooutzs               ┆ Arlo        ┆ 134.08      │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ Pukachu I choose you! ┆ Christopher ┆ 119.74      │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ Raven-ous             ┆ Moon        ┆ 117.2       │
│ 2025   ┆ 17   ┆ Dilly Dilly ┆ Tompa Bae             ┆ Jesse       ┆ 74.88       │
└────────┴──────┴─────────────┴───────────────────────┴─────────────┴─────────────┘

time: 94 ms (started: 2026-07-23 17:37:58 -05:00)

## Example 4: Average Scoring by Position by Team

Shows average weekly scoring by position for each team in the league, grouped by team name. Flex slot (`W/R/T`) is treated as its own position (`FLEX`).

In [ ]:
# Example 4: Average scoring by position by team (team name)
# FLEX handling: W/R/T is treated as FLEX.

roster_df = maybe_load("yhnfl.roster_entries")
stats_df = maybe_load("yhnfl.player_stats_weekly")
team_df = maybe_load("yahoo_common.team")
weekly_points = maybe_load("yhnfl.matchups")

if roster_df is None or stats_df is None or team_df is None:
    print("Required tables are not available.")
else:
    avg_scoring_by_team_position = average_scoring_by_position_by_team(
        roster_df=roster_df,
        stats_df=stats_df,
        team_df=team_df,
        weekly_points=weekly_points,
    )

    print("Average scoring by position for each team (team name view):")
    show_table(avg_scoring_by_team_position)

    league_avg_by_position = league_average_by_position(avg_scoring_by_team_position)

    print("\nLeague average by position:")
    show_table(league_avg_by_position)

    health = player_points_health(stats_df=stats_df, roster_df=roster_df)
    if health["non_zero_fantasy_points"] == 0 and health.get("non_zero_roster_points", 0) == 0:
        print("\nNote: all position scoring is currently 0.0 because player-level points are missing in source tables.")
        print("Team-level weekly scoring (matchups) can still be valid while slot-level scoring is unavailable.")

Average scoring by position for each team (team name view):

shape: (72, 10)
┌────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ season ┆ team_na ┆ positio ┆ avg_poi ┆ median_ ┆ min_wee ┆ max_wee ┆ avg_sta ┆ weeks_c ┆ avg_pct │
│ ---    ┆ me      ┆ n       ┆ nts_per ┆ points_ ┆ k_point ┆ k_point ┆ rters   ┆ ounted  ┆ _of_tea │
│ i64    ┆ ---     ┆ ---     ┆ _week   ┆ per_wee ┆ s       ┆ s       ┆ ---     ┆ ---     ┆ m_point │
│        ┆ str     ┆ str     ┆ ---     ┆ k       ┆ ---     ┆ ---     ┆ f64     ┆ u32     ┆ s       │
│        ┆         ┆         ┆ f64     ┆ ---     ┆ f64     ┆ f64     ┆         ┆         ┆ ---     │
│        ┆         ┆         ┆         ┆ f64     ┆         ┆         ┆         ┆         ┆ f64     │
╞════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│ 2025   ┆ Action  ┆ QB      ┆ 22.15   ┆ 20.27   ┆ 10.32   ┆ 42.92   ┆ 1.0     ┆ 16      ┆ 16.35   │
│        ┆ is the  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Juice   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Action  ┆ RB      ┆ 36.01   ┆ 34.6    ┆ 5.6     ┆ 68.0    ┆ 2.0     ┆ 16      ┆ 26.21   │
│        ┆ is the  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Juice   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Action  ┆ WR      ┆ 47.13   ┆ 48.25   ┆ 17.8    ┆ 69.9    ┆ 3.0     ┆ 16      ┆ 34.7    │
│        ┆ is the  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Juice   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Action  ┆ TE      ┆ 8.36    ┆ 6.4     ┆ 1.2     ┆ 19.5    ┆ 1.0     ┆ 16      ┆ 6.35    │
│        ┆ is the  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Juice   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Action  ┆ FLEX    ┆ 14.71   ┆ 13.85   ┆ 3.0     ┆ 32.5    ┆ 1.0     ┆ 16      ┆ 10.66   │
│        ┆ is the  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Juice   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Action  ┆ DEF     ┆ 7.62    ┆ 7.5     ┆ 0.0     ┆ 16.0    ┆ 1.0     ┆ 16      ┆ 5.73    │
│        ┆ is the  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Juice   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Alameda ┆ QB      ┆ 16.96   ┆ 15.6    ┆ 4.74    ┆ 33.3    ┆ 1.0     ┆ 17      ┆ 14.85   │
│        ┆ All-Sta ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ rs      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Alameda ┆ RB      ┆ 31.26   ┆ 32.1    ┆ 6.2     ┆ 50.1    ┆ 2.0     ┆ 17      ┆ 26.91   │
│        ┆ All-Sta ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ rs      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Alameda ┆ WR      ┆ 35.38   ┆ 35.8    ┆ 15.5    ┆ 67.3    ┆ 3.0     ┆ 17      ┆ 29.43   │
│        ┆ All-Sta ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ rs      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Alameda ┆ TE      ┆ 15.32   ┆ 11.5    ┆ 3.7     ┆ 48.3    ┆ 1.0     ┆ 17      ┆ 13.31   │
│        ┆ All-Sta ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ rs      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Alameda ┆ FLEX    ┆ 12.61   ┆ 11.4    ┆ 0.0     ┆ 33.9    ┆ 1.0     ┆ 17      ┆ 10.16   │
│        ┆ All-Sta ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ rs      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Alameda ┆ DEF     ┆ 7.18    ┆ 6.0     ┆ 0.0     ┆ 23.0    ┆ 1.0     ┆ 17      ┆ 5.33    │
│        ┆ All-Sta ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ rs      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ DaSaint ┆ QB      ┆ 24.36   ┆ 23.22   ┆ 6.9     ┆ 49.68   ┆ 1.0     ┆ 17      ┆ 19.76   │
│        ┆ s       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ DaSaint ┆ RB      ┆ 25.04   ┆ 26.2    ┆ 8.4     ┆ 47.8    ┆ 2.0     ┆ 17      ┆ 20.22   │
│        ┆ s       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ DaSaint ┆ WR      ┆ 44.67   ┆ 44.1    ┆ 20.2    ┆ 74.1    ┆ 3.0     ┆ 17      ┆ 35.91   │
│        ┆ s       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ DaSaint ┆ TE      ┆ 10.69   ┆ 9.2     ┆ 1.6     ┆ 24.1    ┆ 1.0     ┆ 17      ┆ 8.95    │
│        ┆ s       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ DaSaint ┆ FLEX    ┆ 10.11   ┆ 6.6     ┆ 0.1     ┆ 31.5    ┆ 1.0     ┆ 17      ┆ 8.94    │
│        ┆ s       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ DaSaint ┆ DEF     ┆ 7.41    ┆ 6.0     ┆ 0.0     ┆ 18.0    ┆ 1.0     ┆ 17      ┆ 6.22    │
│        ┆ s       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ I am    ┆ QB      ┆ 15.72   ┆ 14.7    ┆ 4.08    ┆ 35.2    ┆ 1.0     ┆ 17      ┆ 13.62   │
│        ┆ the     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Tank    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ I am    ┆ RB      ┆ 26.97   ┆ 26.7    ┆ 11.3    ┆ 40.4    ┆ 2.0     ┆ 17      ┆ 23.7    │
│        ┆ the     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Tank    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ I am    ┆ WR      ┆ 34.59   ┆ 33.4    ┆ 10.1    ┆ 62.3    ┆ 3.0     ┆ 17      ┆ 30.59   │
│        ┆ the     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Tank    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ I am    ┆ TE      ┆ 19.12   ┆ 16.5    ┆ 6.7     ┆ 42.4    ┆ 1.0     ┆ 17      ┆ 16.54   │
│        ┆ the     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Tank    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ I am    ┆ FLEX    ┆ 10.45   ┆ 8.7     ┆ 1.0     ┆ 27.8    ┆ 1.0     ┆ 17      ┆ 8.9     │
│        ┆ the     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Tank    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ I am    ┆ DEF     ┆ 8.18    ┆ 6.0     ┆ 0.0     ┆ 30.0    ┆ 1.0     ┆ 17      ┆ 6.66    │
│        ┆ the     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Tank    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Kyler   ┆ QB      ┆ 16.1    ┆ 17.66   ┆ 3.12    ┆ 33.2    ┆ 1.0     ┆ 17      ┆ 15.72   │
│        ┆ the     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Creator ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ …      ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       │
│ 2025   ┆ Raven-o ┆ DEF     ┆ 10.47   ┆ 8.0     ┆ 2.0     ┆ 30.0    ┆ 1.0     ┆ 17      ┆ 9.15    │
│        ┆ us      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Rome    ┆ QB      ┆ 20.77   ┆ 21.66   ┆ 5.68    ┆ 38.7    ┆ 1.0     ┆ 17      ┆ 15.38   │
│        ┆ Sweet   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Rome    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Rome    ┆ RB      ┆ 44.46   ┆ 39.7    ┆ 13.5    ┆ 97.8    ┆ 2.0     ┆ 17      ┆ 30.93   │
│        ┆ Sweet   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Rome    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Rome    ┆ WR      ┆ 44.92   ┆ 45.2    ┆ 17.3    ┆ 103.3   ┆ 3.0     ┆ 17      ┆ 30.44   │
│        ┆ Sweet   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Rome    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Rome    ┆ TE      ┆ 10.88   ┆ 7.7     ┆ 0.0     ┆ 50.6    ┆ 1.0     ┆ 17      ┆ 7.89    │
│        ┆ Sweet   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Rome    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Rome    ┆ FLEX    ┆ 13.63   ┆ 12.9    ┆ 5.2     ┆ 27.6    ┆ 1.0     ┆ 17      ┆ 9.37    │
│        ┆ Sweet   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Rome    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Rome    ┆ DEF     ┆ 9.0     ┆ 6.0     ┆ -4.0    ┆ 21.0    ┆ 1.0     ┆ 17      ┆ 6.0     │
│        ┆ Sweet   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Rome    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Tompa   ┆ QB      ┆ 18.59   ┆ 20.04   ┆ 7.04    ┆ 28.88   ┆ 1.0     ┆ 17      ┆ 17.04   │
│        ┆ Bae     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Tompa   ┆ RB      ┆ 30.35   ┆ 28.5    ┆ 14.9    ┆ 55.0    ┆ 2.0     ┆ 17      ┆ 27.16   │
│        ┆ Bae     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Tompa   ┆ WR      ┆ 34.62   ┆ 38.7    ┆ 14.6    ┆ 50.7    ┆ 3.0     ┆ 17      ┆ 30.53   │
│        ┆ Bae     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Tompa   ┆ TE      ┆ 10.22   ┆ 8.4     ┆ 3.3     ┆ 21.7    ┆ 1.0     ┆ 17      ┆ 9.19    │
│        ┆ Bae     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Tompa   ┆ FLEX    ┆ 10.87   ┆ 8.3     ┆ 0.0     ┆ 24.8    ┆ 1.0     ┆ 17      ┆ 10.1    │
│        ┆ Bae     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Tompa   ┆ DEF     ┆ 6.82    ┆ 5.0     ┆ 0.0     ┆ 17.0    ┆ 1.0     ┆ 17      ┆ 5.97    │
│        ┆ Bae     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Zero    ┆ QB      ┆ 19.93   ┆ 18.78   ┆ 7.8     ┆ 38.96   ┆ 1.0     ┆ 17      ┆ 16.03   │
│        ┆ Dark    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Purdy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Zero    ┆ RB      ┆ 35.36   ┆ 39.7    ┆ 20.2    ┆ 48.1    ┆ 2.0     ┆ 17      ┆ 29.1    │
│        ┆ Dark    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Purdy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Zero    ┆ WR      ┆ 36.63   ┆ 37.9    ┆ 11.6    ┆ 58.3    ┆ 3.0     ┆ 17      ┆ 29.2    │
│        ┆ Dark    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Purdy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Zero    ┆ TE      ┆ 13.36   ┆ 12.5    ┆ 0.0     ┆ 29.5    ┆ 1.0     ┆ 17      ┆ 10.28   │
│        ┆ Dark    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Purdy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Zero    ┆ FLEX    ┆ 11.56   ┆ 11.7    ┆ 1.6     ┆ 38.5    ┆ 1.0     ┆ 17      ┆ 8.85    │
│        ┆ Dark    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Purdy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ Zero    ┆ DEF     ┆ 7.76    ┆ 7.0     ┆ 0.0     ┆ 16.0    ┆ 1.0     ┆ 17      ┆ 6.55    │
│        ┆ Dark    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│        ┆ Purdy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ 2025   ┆ oooutzs ┆ QB      ┆ 20.85   ┆ 20.28   ┆ 13.1    ┆ 31.46   ┆ 1.0     ┆ 17      ┆ 17.24   │
│ 2025   ┆ oooutzs ┆ RB      ┆ 24.69   ┆ 23.5    ┆ 11.4    ┆ 40.9    ┆ 2.0     ┆ 17      ┆ 20.17   │
│ 2025   ┆ oooutzs ┆ WR      ┆ 46.75   ┆ 42.1    ┆ 15.5    ┆ 98.8    ┆ 3.0     ┆ 17      ┆ 36.62   │
│ 2025   ┆ oooutzs ┆ TE      ┆ 11.22   ┆ 10.1    ┆ 1.9     ┆ 29.5    ┆ 1.0     ┆ 17      ┆ 8.68    │
│ 2025   ┆ oooutzs ┆ FLEX    ┆ 13.16   ┆ 10.6    ┆ 0.8     ┆ 38.9    ┆ 1.0     ┆ 17      ┆ 10.29   │
│ 2025   ┆ oooutzs ┆ DEF     ┆ 8.29    ┆ 8.0     ┆ -3.0    ┆ 21.0    ┆ 1.0     ┆ 17      ┆ 7.0     │
└────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘

League average by position:

shape: (6, 4)
┌────────┬──────────┬────────────────────────────┬───────────────────────────────┐
│ season ┆ position ┆ league_avg_points_per_week ┆ league_avg_pct_of_team_points │
│ ---    ┆ ---      ┆ ---                        ┆ ---                           │
│ i64    ┆ str      ┆ f64                        ┆ f64                           │
╞════════╪══════════╪════════════════════════════╪═══════════════════════════════╡
│ 2025   ┆ QB       ┆ 19.53                      ┆ 16.25                         │
│ 2025   ┆ RB       ┆ 31.44                      ┆ 25.78                         │
│ 2025   ┆ WR       ┆ 40.13                      ┆ 32.39                         │
│ 2025   ┆ TE       ┆ 11.52                      ┆ 9.58                          │
│ 2025   ┆ FLEX     ┆ 12.05                      ┆ 9.8                           │
│ 2025   ┆ DEF      ┆ 7.57                       ┆ 6.2                           │
└────────┴──────────┴────────────────────────────┴───────────────────────────────┘

time: 94 ms (started: 2026-07-23 17:40:29 -05:00)